# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# CAVEATS:
#  - Keeping it here for the record: the pretty-format-toml from here:
#    https://github.com/macisamuele/language-formatters-pre-commit-hooks
#    kills comments in the TOML files, hence we're stopping using it.

repos:
  # Ruff linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.283
    hooks:
      - id: ruff
        name: Lint with Ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
            /testdata/|
            /DEPENDENCIES|
            gradlew
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            /testdata/|
            /DEPENDENCIES
          )
      - id: check-yaml
        exclude: test_schemas.yaml|.clang-format
      - id: check-added-large-files

  # Strict formatting for our python code.
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Format code with Black
        exclude: |
          (?x)(
            /testdata/
          )

  # Sorting imports in python code.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort imports with isort
        exclude: |
          (?x)(
            /testdata/
          )
